# Generated by Django 4.2.4 on 2023-10-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingtestModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('partTitle', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('finishedAt', models.DateField()),
                ('explain', models.TextField()),
                ('code', models.TextField()),
                ('result', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
