# Generated by Django 4.2.4 on 2023-10-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingtestmodel',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codingtestmodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codingtestmodel',
            name='explain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codingtestmodel',
            name='finishedAt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codingtestmodel',
            name='partTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='codingtestmodel',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codingtestmodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
