# Generated by Django 4.2.4 on 2023-10-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_alter_codingtestmodel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingtestmodel',
            name='finishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
