# Generated by Django 4.2.4 on 2023-10-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_alter_codingtestmodel_finishedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingtestmodel',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
