# Generated by Django 4.2.4 on 2023-10-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_codingtestmodel_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingtestmodel',
            name='_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codingtestmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
