# Generated by Django 4.2.4 on 2023-10-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_codingtestmodel__id_alter_codingtestmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingtestmodel',
            name='_id',
            field=models.IntegerField(default=-1),
        ),
    ]
