# Generated by Django 4.2.4 on 2023-10-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_alter_codingtestmodel__id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodingtestModel',
            new_name='CodingTestProblems',
        ),
    ]
