# Generated by Django 4.2.4 on 2023-10-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_rename_codingtestmodel_codingtestproblems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingtestproblems',
            name='id',
        ),
        migrations.AlterField(
            model_name='codingtestproblems',
            name='_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
