# Generated by Django 4.2.4 on 2023-10-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_remove_codingtestproblems_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codingtestproblems',
            old_name='_id',
            new_name='id',
        ),
    ]
