# Generated by Django 4.2.4 on 2023-10-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0009_rename__id_codingtestproblems_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredBbs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=9999)),
            ],
        ),
    ]
