# Generated by Django 4.2.4 on 2023-10-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0010_registeredbbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredbbs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
