# Generated by Django 4.2.4 on 2023-10-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_alter_registeredbbs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredbbs',
            name='body',
            field=models.TextField(max_length=9999),
        ),
    ]
