# Generated by Django 4.2.4 on 2023-10-30 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0012_alter_registeredbbs_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredbbs',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
