# Generated by Django 4.2.4 on 2023-10-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0013_alter_registeredbbs_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BbsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
